# Generated by Django 4.2.4 on 2023-08-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0002_alter_parseddata_booking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('parsed_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Photos.parseddata')),
            ],
        ),
    ]
